//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_ANGULAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_DATOS_BASICOS
    {
        public int ID { get; set; }
        public Nullable<int> CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> REFERENCIA { get; set; }
        public string UBICACION { get; set; }
        public string SEDE_BODEGA { get; set; }
        public byte[] IMAGEN { get; set; }
    }
}
